name: Build

on:
  schedule:
    - cron: '27 5 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]


jobs:
  ros-humble:
    uses: ./.github/workflows/docker.yml
    permissions:
      packages: write
      id-token: write
    with:
      image: ros-humble

  ros-humble-simulation:
    needs: [ros-humble]
    uses: ./.github/workflows/docker.yml
    permissions:
      packages: write
      id-token: write
    with:
      image: ros-humble-simulation