name: Docker

on:
  schedule:
    - cron: '27 5 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io


jobs:
  build-ros-humble:
    uses: ./.github/workflows/docker.yml
    with:
      image: ros-humble

  build-ros-humble-simulation:
    needs: [build-ros-humble]
    uses: ./.github/workflows/docker.yml
    with:
      image: ros-humble-simulation